{% set name = "ecdsa" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 190348041559e21b22a1d65cee485282ca11a6f81d503fddb84d5017e9ed1e49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - gmpy2
    - python >=3.3
    - six >=1.9.0

test:
  imports:
    - ecdsa

about:
  home: http://github.com/warner/python-ecdsa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ECDSA cryptographic signature library (pure python)

extra:
  recipe-maintainers:
    - mariusvniekerk
    - m-rossi
