{% set name = "ecdsa" %}
{% set version = "0.13.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 163c80b064a763ea733870feb96f9dd9b92216cfcacd374837af18e4e8ec3d4d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - ecdsa

about:
  home: http://github.com/warner/python-ecdsa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ECDSA cryptographic signature library (pure python)

extra:
  recipe-maintainers:
    - mariusvniekerk
