{% set name = "ecdsa" %}
{% set version = "0.14.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64c613005f13efec6541bb0a33290d0d03c27abab5f15fbab20fb0ee162bdd8e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - ecdsa

about:
  home: http://github.com/warner/python-ecdsa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: ECDSA cryptographic signature library (pure python)

extra:
  recipe-maintainers:
    - mariusvniekerk
